# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dl-rake-latex}
  s.version = "5.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Love"]
  s.date = %q{2011-08-01}
  s.default_executable = %q{gnuplot-latex-fonts}
  s.description = %q{http://devel.softeng.ox.ac.uk/trac/softeng/wiki/Utilities/RakeLatex}
  s.email = %q{david@homeunix.org.uk}
  s.executables = ["gnuplot-latex-fonts"]
  s.extra_rdoc_files = [
    "ChangeLog",
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "ChangeLog",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/gnuplot-latex-fonts",
    "lib/rake-latex.rb",
    "lib/rake-latex/figures.rb",
    "lib/rake-latex/latex.rb",
    "lib/rake-latex/vega.rb",
    "test/helper.rb",
    "test/test_rake-latex.rb"
  ]
  s.homepage = %q{http://github.com/dlove24/rake-latex}
  s.licenses = ["GNU"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Rake LaTeX task developed by the Software Engineering group at the University of Oxford}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
  end
end

